# Use a imagem oficial do Node.js
FROM node:14

# Defina o diretório de trabalho
WORKDIR /var/www/html/controle-series

# Copie o package.json e package-lock.json para instalar dependências
COPY package*.json ./

# Instale as dependências
RUN npm install

# Copie o restante dos arquivos do projeto
COPY . .